apiVersion: apps/v1
kind: Deployment
metadata:
  name: bijintest
  annotations:
     "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bijintest
  template:
    metadata:
      labels:
        app: bijintest
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/path: "/bijintest/metrics"
         prometheus.io/port: "8080"
         prometheus.io/scrape: "true"
    spec:
      volumes:
      - name: app-config
        configMap:
          name: app-config
      containers:
      - name: bijintest
        image: repo.imp.com/imptest/bijintest:sprint14project-dev-apps
        imagePullPolicy: Always
        volumeMounts:
        - name: app-config
          mountPath: /usr/app/src/main/resources/config
        ports:
        - containerPort: 8091
        - containerPort: 8090
        - containerPort: 8080
        env: 
        - name: JAEGER_SERVICE_NAME
          value: bijintest
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-collector.observability.svc:14268/api/traces'
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: '1'
        - name: JAEGER_REPORTER_LOG_SPANS
          value: 'true'
        - name: JAEGER_TAGS
          value: 'version=${VERSION}'