apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: bijintest
  name: bijintest
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 2m
      port: prom
      scrapeTimeout: 2m
    - interval1: 30s
      port: http1
  namespaceSelector:
    matchNames:
    - sprint14project-dev-app
    - sprint14project-devops-app
    
  selector:
    matchLabels:
      app: bijintest